Repository PaGr0m/RogueLike, pull requests merged in 2020-06, with the labels that each got.

#73 Fix inventory-related bugs
  src/main/java/ru/itmo/roguelike/characters/Player.java
  src/main/java/ru/itmo/roguelike/characters/inventory/Inventory.java
  src/main/java/ru/itmo/roguelike/manager/gamemanager/GameManager.java
  src/main/java/ru/itmo/roguelike/manager/uimanager/UIManager.java
Labels: enhancement

#71 add save-load support
  src/main/java/ru/itmo/roguelike/Application.java
  src/main/java/ru/itmo/roguelike/characters/Actor.java
  src/main/java/ru/itmo/roguelike/characters/Player.java
  src/main/java/ru/itmo/roguelike/characters/attack/Attack.java
  src/main/java/ru/itmo/roguelike/characters/attack/FireballAttack.java
  src/main/java/ru/itmo/roguelike/characters/attack/SwordAttack.java
  src/main/java/ru/itmo/roguelike/characters/inventory/Inventory.java
  src/main/java/ru/itmo/roguelike/characters/inventory/Usable.java
  src/main/java/ru/itmo/roguelike/characters/movement/MoverDrunkStraight.java
  src/main/java/ru/itmo/roguelike/exceptions/DieException.java
  src/main/java/ru/itmo/roguelike/field/MobPositionGenerator.java
  src/main/java/ru/itmo/roguelike/input/Event.java
  src/main/java/ru/itmo/roguelike/input/InputHandler.java
  src/main/java/ru/itmo/roguelike/items/BonusType.java
  src/main/java/ru/itmo/roguelike/items/Collectible.java
  src/main/java/ru/itmo/roguelike/items/MedKit.java
  src/main/java/ru/itmo/roguelike/items/SpeedBoosters.java
  src/main/java/ru/itmo/roguelike/items/Teleport.java
  src/main/java/ru/itmo/roguelike/manager/actormanager/ActorManager.java
  src/main/java/ru/itmo/roguelike/manager/actormanager/MobManager.java
  src/main/java/ru/itmo/roguelike/manager/actormanager/ProjectileManager.java
  src/main/java/ru/itmo/roguelike/manager/collidemanager/CollideManager.java
  src/main/java/ru/itmo/roguelike/manager/gamemanager/GameManager.java
  src/main/java/ru/itmo/roguelike/manager/gamemanager/GameState.java
  src/main/java/ru/itmo/roguelike/render/Camera.java
  src/main/java/ru/itmo/roguelike/render/drawable/Drawable.java
  src/main/java/ru/itmo/roguelike/render/particles/TextWithPoint.java
  src/main/java/ru/itmo/roguelike/settings/GameSettings.java
  src/main/java/ru/itmo/roguelike/utils/MathUtils.java
  test.mapfile_save
Labels: enhancement

#74 Ignore save files
  .gitignore
Labels: bug

#76 rework ui
  src/main/java/ru/itmo/roguelike/characters/Player.java
  src/main/java/ru/itmo/roguelike/characters/attack/FireballAttack.java
  src/main/java/ru/itmo/roguelike/characters/attack/SwordAttack.java
  src/main/java/ru/itmo/roguelike/characters/inventory/Inventory.java
  src/main/java/ru/itmo/roguelike/characters/inventory/Usable.java
  src/main/java/ru/itmo/roguelike/field/MobPositionGenerator.java
  src/main/java/ru/itmo/roguelike/items/Collectible.java
  src/main/java/ru/itmo/roguelike/items/MedKit.java
  src/main/java/ru/itmo/roguelike/items/Teleport.java
  src/main/java/ru/itmo/roguelike/manager/gamemanager/GameManager.java
  src/main/java/ru/itmo/roguelike/manager/uimanager/UIManager.java
  src/main/java/ru/itmo/roguelike/render/JexerRenderEngine.java
  src/main/java/ru/itmo/roguelike/utils/FileUtils.java
  src/main/java/ru/itmo/roguelike/utils/FuncUtils.java
  src/main/resources/fonts/minecraft.ttf
Labels: enhancement

#79 fix reset
  src/main/java/ru/itmo/roguelike/characters/Player.java
  src/main/java/ru/itmo/roguelike/input/InputHandler.java
  src/main/java/ru/itmo/roguelike/manager/gamemanager/GameManager.java
  src/main/java/ru/itmo/roguelike/manager/gamemanager/GameState.java
Labels: bug

#80 Reject using med-kit when max health
  src/main/java/ru/itmo/roguelike/characters/Actor.java
  src/main/java/ru/itmo/roguelike/items/Collectible.java
  src/main/java/ru/itmo/roguelike/items/MedKit.java
Labels: bug

#83 Add armor
  src/main/java/ru/itmo/roguelike/characters/Actor.java
  src/main/java/ru/itmo/roguelike/characters/inventory/Usable.java
  src/main/java/ru/itmo/roguelike/items/Armor.java
  src/main/java/ru/itmo/roguelike/items/LeatherJacket.java
Labels: enhancement

#82 Drop items
  src/main/java/ru/itmo/roguelike/characters/Player.java
  src/main/java/ru/itmo/roguelike/characters/inventory/Droppable.java
  src/main/java/ru/itmo/roguelike/characters/inventory/Usable.java
  src/main/java/ru/itmo/roguelike/input/EventStatus.java
  src/main/java/ru/itmo/roguelike/input/InputHandler.java
  src/main/java/ru/itmo/roguelike/items/Collectible.java
  src/main/java/ru/itmo/roguelike/manager/gamemanager/GameManager.java
Labels: enhancement

#84 add pause <proposal>
  src/main/java/ru/itmo/roguelike/characters/Actor.java
  src/main/java/ru/itmo/roguelike/characters/Player.java
  src/main/java/ru/itmo/roguelike/characters/attack/FireballAttack.java
  src/main/java/ru/itmo/roguelike/characters/attack/SwordAttack.java
  src/main/java/ru/itmo/roguelike/characters/inventory/Usable.java
  src/main/java/ru/itmo/roguelike/characters/mobs/Slime.java
  src/main/java/ru/itmo/roguelike/characters/movement/MoverEmbarrassment.java
  src/main/java/ru/itmo/roguelike/input/Event.java
  src/main/java/ru/itmo/roguelike/input/EventStatus.java
  src/main/java/ru/itmo/roguelike/input/InputHandler.java
  src/main/java/ru/itmo/roguelike/items/Armor.java
  src/main/java/ru/itmo/roguelike/items/MedKit.java
  src/main/java/ru/itmo/roguelike/manager/eventmanager/Event.java
  src/main/java/ru/itmo/roguelike/manager/eventmanager/EventManager.java
  src/main/java/ru/itmo/roguelike/manager/gamemanager/GameManager.java
  src/main/java/ru/itmo/roguelike/manager/gamemanager/GameState.java
  src/main/java/ru/itmo/roguelike/manager/uimanager/UIManager.java
  src/main/java/ru/itmo/roguelike/render/JexerRenderEngine.java
  src/main/java/ru/itmo/roguelike/render/RenderEngine.java
Labels: proposal

#88 Boss: first iteration
  src/main/java/ru/itmo/roguelike/Collidable.java
  src/main/java/ru/itmo/roguelike/characters/Actor.java
  src/main/java/ru/itmo/roguelike/characters/Player.java
  src/main/java/ru/itmo/roguelike/characters/mobs/Boss.java
  src/main/java/ru/itmo/roguelike/characters/mobs/Enemy.java
  src/main/java/ru/itmo/roguelike/characters/mobs/PersonX.java
  src/main/java/ru/itmo/roguelike/characters/mobs/strategy/RandomWalkBehavior.java
  src/main/java/ru/itmo/roguelike/field/Field.java
  src/main/java/ru/itmo/roguelike/render/Camera.java
  src/main/java/ru/itmo/roguelike/render/drawable/Drawable.java
  src/main/java/ru/itmo/roguelike/render/drawable/DrawableDescriptor.java
  src/main/java/ru/itmo/roguelike/utils/BoundingBox.java
Labels: boss, enhancement
